### ISSUE TITLE
我在用dubbo和当前版本的通用mapper结合使用时遇到的一个问题

### ISSUE THREAD

**Issue by syncml** [abel533/Mapper#106]
dubbo provider:

```
@Service("IProvinceService")
public class ProvinceService extends BaseService<Province> implements IProvinceService {

}
```

dubbo consumer:

```
public class ProvinceServiceTest extends BasicTest{

    @Reference
    IProvinceService provinceService;

    @Test
    public void test(){
        Example example = new Example(Province.class);
        Example.Criteria criteria = example.createCriteria();
        criteria.andGreaterThan("id",10);
        provinceService.selectByExample(example);
    }
}
```

运行时报错：

```
java.lang.RuntimeException: 无法获取实体类com.xxx.domain.Province对应的表名!
	at tk.mybatis.mapper.mapperhelper.EntityHelper.getEntityTable(EntityHelper.java:65)
	at tk.mybatis.mapper.entity.Example.<init>(Example.java:93)
	at tk.mybatis.mapper.entity.Example.<init>(Example.java:78)
	at tk.mybatis.mapper.entity.Example.<init>(Example.java:68)
```

在服务端调用没问题，是不是意味着Example只能在注册provider那个地方才能使用呢？没有了Example，用起来好不方便，项目又是dubbo做服务治理的。

**Comment by abel533** [comment]
暂时是不行了，或者封装一个自己的example。。符合要求的都能使用。

4.x 版本会考虑将Example分离出去。

**Comment by syncml** [comment]
谢谢，期待
