### ISSUE TITLE
集成Spring-Boot 2后访问出现的异常

### ISSUE THREAD

**Issue by moonshy** [abel533/Mapper#258]
java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.base.BaseSelectProvider.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_162]
	at java.lang.Class.newInstance(Class.java:412) ~[na:1.8.0_162]
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.invokeProviderMethod(ProviderSqlSource.java:165) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:116) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.getBoundSql(ProviderSqlSource.java:102) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:292) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:81) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[mybatis-3.4.6.jar:3.4.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.2.jar:1.3.2]
	at com.sun.proxy.$Proxy66.selectList(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230) ~[mybatis-spring-1.3.2.jar:1.3.2]
以上异常是在集成通用mapper后，启动项目成功的。但是查询数据时报错。现在我不知道是什么因为配置问题还是什么原因。还请帮忙看一下！谢谢

**Comment by qiuzhi** [comment]
同上，好像不是2.0的问题，我不用@MapperScan注解一样配置不成功

**Comment by moonshy** [comment]
@qiuzhi 是的。我也试过不写@MapperScan问题依旧

**Comment by abel533** [comment]
1. 用2.0.1版本。
2. 如果用mapperscan注解，就用tk.mybatis包的。

**Comment by moonshy** [comment]
@abel533  我刚试了一下，去掉启动类上的MapperScan好像又可以了。估计之前是我这边环境的问题。谢谢大神

**Comment by qiuzhi** [comment]
对的，这样是没问题的，要用@Mapper注解，用原生的@MapperScan是不行的

**Comment by abel533** [comment]
`@MapperScan` 注解需要配合 `@Mapper` 注解. 不管用 tk 的还是 org 的都需要。。
