### ISSUE TITLE
start 2.0.2 版本 通用update 语句报错：不支持的特性

### ISSUE THREAD

**Issue by zhqiang-li** [abel533/Mapper#306]
2.0.2版本：
    @UpdateProvider(
        type = BaseUpdateProvider.class,
        method = "dynamicSQL"
    )
    int updateByPrimaryKey(T var1);
1.2.4版本：
    @UpdateProvider(
        type = BaseUpdateProvider.class,
        method = "dynamicSQL"
    )
    @Options(
        useCache = false,
        useGeneratedKeys = false
    )
    int updateByPrimaryKey(T var1);

1.2.4主键使用的@GeneratedValue(generator = "UUID")
2.0.2主键使用的@KeySql(genId = UuidGenId.class) 默认 useGeneratedKeys 也是为false的

1.2.4版本时正常的，2.0.2不知为何报错。之前怀疑是set id=id 已设置 id 不更新，生成的SQL：

==>  Preparing: UPDATE sys_dict_type SET name = ?,code = ? WHERE GUID = ? 
==> Parameters: 测试通用增删改查(String), testCrud(String), 23131(String)
<==    Updates: 1

Caused by: java.sql.SQLException: 不支持的特性: getMetaData
	at oracle.jdbc.driver.ArrayDataResultSet.getMetaData(ArrayDataResultSet.java:1411)
	at com.alibaba.druid.wall.WallFilter.preprocessResultSet(WallFilter.java:1467)
	at com.alibaba.druid.wall.WallFilter.statement_getGeneratedKeys(WallFilter.java:719)
	at com.alibaba.druid.filter.FilterChainImpl.statement_getGeneratedKeys(FilterChainImpl.java:2730)
	at com.alibaba.druid.filter.FilterAdapter.statement_getGeneratedKeys(FilterAdapter.java:2546)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_getGeneratedKeys(FilterEventAdapter.java:415)
	at com.alibaba.druid.filter.FilterChainImpl.statement_getGeneratedKeys(FilterChainImpl.java:2730)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.getGeneratedKeys(StatementProxyImpl.java:309)
	at com.alibaba.druid.pool.DruidPooledStatement.getGeneratedKeys(DruidPooledStatement.java:760)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:78)
	at com.sun.proxy.$Proxy181.getGeneratedKeys(Unknown Source)
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.processBatch(Jdbc3KeyGenerator.java:63)
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.processAfter(Jdbc3KeyGenerator.java:57)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:50)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy179.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 46 more

@abel533  大神 有时间帮忙看下，谢谢！

**Comment by zhqiang-li** [comment]
@options(
useCache = false,
useGeneratedKeys = false
)

mybatis二级缓存  useCache = true 的错误，设置为false 即可

mybatis:
  configuration:
    cache-enabled: false

或者 mybatis.xml中配置：

<setting name="cacheEnabled" value="false"/>

这个是全局的设置，貌似tkmybatis没有提供单独通用方法设置不使二级缓存

**Comment by zhougod520** [comment]
我也遇到了，更新的update语句不知道为啥自己带了id =id 的条件：
