### ISSUE TITLE
@KeySql oracle 回写问题

### ISSUE THREAD

**Issue by YorkWong** [abel533/Mapper#310]
您好:
   最近我在oracle环境下使用@KeySql来自定义主键生成
   ```
@KeySql(genId = MybatisGenId.class, order = ORDER.BEFORE)
```
oracle表设计仲 主键是一个NUMBER类型, java中使用的是Long
使用mapper的Insert是可以成功插入的. 但插入后回写主键时报出以下错误

```
Caused by: org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column #1 from result set.  Cause: java.sql.SQLException: 无效的列类型: getLong not implemented for class oracle.jdbc.driver.T4CRowidAccessor
```
完整信息如下
```
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column #1 from result set.  Cause: java.sql.SQLException: 无效的列类型: getLong not implemented for class oracle.jdbc.driver.T4CRowidAccessor

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy86.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:58)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy90.insertSelective(Unknown Source)
```

环境如下:
oracle 11g
ojdbc.version=10.2.0.5.0
spring boot: 1.5.9
通用mapper: 4.02

**Comment by YorkWong** [comment]
已解决, 
问题在于mybatis.configuration.use-generated-keys=true的影响.设置成false就可以了,可能是一开始我理解优先级局限在@Keysql 那个useGeneratedKeys吧.没想到也受到mybatis的config的影响
