### ISSUE TITLE
Cause: java. lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseInsertProvider

### ISSUE THREAD

**Issue by lengmianshi** [abel533/Mapper#311]
springboot 1.5 + mapperV 3.4.0。调用Mapper接口（实际上是MyMapper接口，MyMapper接口继承Mapper接口）的insert时可能会出现上面的错误。大部分正常，但一旦报错就会循环报错。部分代码如下：
```java
public class BaseService <T>{

        @Autowired
        protected MyMapper<T> mapper;

        /**
         * 保存一个实体，null的属性也会保存，不会使用数据库默认值
         */
        public int insert(T entity) {
            return mapper.insert(entity);
        }
｝
```

调用处：
 ```java
                            WgGuessTask task = new WgGuessTask();
                            task.setTaskId(taskId);
                            task.setUserId(userId);
                            task.setCreateTime(new Date());
                            task.setUpdateTime(task.getCreateTime());
                            task.setStatus(0);
                            task.setIsRecharge(0);
                            task.setFailLevel(0);
                            task.setIsShare(0);
                            taskService.insert(task);
```

错误信息：
```
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provide
r.base.BaseInsertProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseInsertProvider        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
        at com.sun.proxy.$Proxy89.insert(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:57)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
        at com.sun.proxy.$Proxy92.insert(Unknown Source)
        at com.qihe.guess.service.BaseService.insert(BaseService.java:18)
        at com.qihe.guess.aync.MessageQueueConsumer.consume(MessageQueueConsumer.java:110)
        at com.qihe.guess.aync.MessageQueueConsumer$$FastClassBySpringCGLIB$$be13f4fe.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provider.base.BaseInsertProvider.dynamicSQL).  Cause: java.
lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseInsertProvider        at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:103)
        at org.apache.ibatis.builder.annotation.ProviderSqlSource.getBoundSql(ProviderSqlSource.java:73)
        at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:292)
        at org.apache.ibatis.executor.statement.BaseStatementHandler.<init>(BaseStatementHandler.java:64)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.<init>(PreparedStatementHandler.java:40)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.<init>(RoutingStatementHandler.java:46)
        at org.apache.ibatis.session.Configuration.newStatementHandler(Configuration.java:545)
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48)
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
        ... 16 common frames omitted
Caused by: java.lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseInsertProvider
        at java.lang.Class.newInstance(Class.java:427)
        at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:85)
        ... 32 common frames omitted
Caused by: java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.base.BaseInsertProvider.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.newInstance(Class.java:412)
        ... 33 common frames omitted
```

**Comment by chinleo** [comment]
我也遇到了, mybatis版本3.4.6. 使用的mapper是mapper-spring-boot-starter-2.0.2.jar包的依赖

**Comment by chinleo** [comment]
@lengmianshi 检查下是不是你的@MapperScan注解用的不是tk.mapper包下的. 我被队友坑了把

**Comment by abel533** [comment]
初始化出错导致的。。。先看楼上回复，再看这里:https://github.com/abel533/Mapper/wiki/faq

**Comment by sanwancoder** [comment]
> MapperScan

需要使用这个注解 
import tk.mybatis.spring.annotation.MapperScan;

**Comment by Neyzoter** [comment]
刚开始用了
```java
import org.mybatis.spring.annotation.MapperScan;
```

后面发现前面的mapper是tk的，改成tk的即可，
```java
import tk.mybatis.spring.annotation.MapperScan;
```

**Comment by tonglin0325** [comment]
用的就是import tk.mybatis.spring.annotation.MapperScan;，但是还是报错
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provider.base.BaseSelectProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseSelectProvider

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy137.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:83)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy138.selectByPrimaryKey(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy141.selectByPrimaryKey(Unknown Source)

**Comment by EalenXie** [comment]
改了之后，正常启动和运行不报错，debug模式启动就报错。
```
Caused by: tk.mybatis.mapper.MapperException: tk.mybatis.mapper.MapperException: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at tk.mybatis.mapper.mapperhelper.MapperHelper.setSqlSource(MapperHelper.java:378) ~[mapper-core-1.1.0.jar:na]
	at tk.mybatis.mapper.mapperhelper.MapperHelper.processMappedStatement(MapperHelper.java:297) ~[mapper-core-1.1.0.jar:na]
	at tk.mybatis.mapper.mapperhelper.MapperHelper.processConfiguration(MapperHelper.java:283) ~[mapper-core-1.1.0.jar:na]
	at tk.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:93) ~[mapper-spring-1.1.0.jar:na]
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	... 16 common frames omitted
Caused by: tk.mybatis.mapper.MapperException: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at tk.mybatis.mapper.mapperhelper.MapperTemplate.setSqlSource(MapperTemplate.java:256) ~[mapper-core-1.1.0.jar:na]
	at tk.mybatis.mapper.mapperhelper.MapperHelper.setSqlSource(MapperHelper.java:375) ~[mapper-core-1.1.0.jar:na]
	... 22 common frames omitted
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at tk.mybatis.mapper.mapperhelper.MapperTemplate.getEntityClass(MapperTemplate.java:170) ~[mapper-core-1.1.0.jar:na]
	at tk.mybatis.mapper.provider.base.BaseSelectProvider.existsWithPrimaryKey(BaseSelectProvider.java:126) ~[mapper-base-1.1.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
	at tk.mybatis.mapper.mapperhelper.MapperTemplate.setSqlSource(MapperTemplate.java:246) ~[mapper-core-1.1.0.jar:na]
	... 23 common frames omitted
 
```

**Comment by starlight36** [comment]
补充一个会导致这个问题的case：

- `tk.mybatis.spring.annotation.MapperScan`注解指定正确
- 自定义的`CommonMapper`在`mapper.mappers`里指定了，并且确认读到了此配置

按照上面的建议，两点都确认了，但问题依然存在。稍微跟进了一下，发现在`ClassPathMapperScanner`执行`doAfterScan`时，实际上无视了`mapper.mappers`指定的mapper类，只处理了默认的Mapper。跟进去发现`ClassPathMapperScanner`里面传入`Config`配置到内部的`MapperHelper`时，并没有任何操作触发自定义的mapper注册，因此相当于注册完全没有生效，确定是一个Bug，由于这个Bug影响会比较大，猜测应该是已知问题。翻翻记录发现在 https://github.com/abel533/Mapper/commit/fefe5df6df82a3dc4dcd866fc6341971b58d0647 这个提交里面修复了这个问题，mapper版本是3.5.3，升级了starter至1.2.4后问题修复。

在[https://github.com/abel533/Mapper/tree/master/spring-boot-starter](https://github.com/abel533/Mapper/tree/master/spring-boot-starter)页面中给出的默认建议版本号1.2.3是有此问题的，也并非Mapper 3.x的最新版，Release note的更新也较为滞后，辛苦适时更新一下~

**Comment by zhengbinger** [comment]
> @lengmianshi 检查下是不是你的@MapperScan注解用的不是tk.mapper包下的. 我被队友坑了把

牛批还是牛批，感谢

**Comment by HuangDayu** [comment]
服务启动时没有任何问题，使用一段时间后，突然就报了这个异常，重启又没有问题了，真尴尬。

**Comment by UnityAlvin** [comment]
> 

我这也是这个原因，感谢！

**Comment by zhangbo1201** [comment]
> 补充一个会导致这个问题的case：
> 
> * `tk.mybatis.spring.annotation.MapperScan`注解指定正确
> * 自定义的`CommonMapper`在`mapper.mappers`里指定了，并且确认读到了此配置
> 
> 按照上面的建议，两点都确认了，但问题依然存在。稍微跟进了一下，发现在`ClassPathMapperScanner`执行`doAfterScan`时，实际上无视了`mapper.mappers`指定的mapper类，只处理了默认的Mapper。跟进去发现`ClassPathMapperScanner`里面传入`Config`配置到内部的`MapperHelper`时，并没有任何操作触发自定义的mapper注册，因此相当于注册完全没有生效，确定是一个Bug，由于这个Bug影响会比较大，猜测应该是已知问题。翻翻记录发现在 [fefe5df](https://github.com/abel533/Mapper/commit/fefe5df6df82a3dc4dcd866fc6341971b58d0647) 这个提交里面修复了这个问题，mapper版本是3.5.3，升级了starter至1.2.4后问题修复。
> 
> 在https://github.com/abel533/Mapper/tree/master/spring-boot-starter页面中给出的默认建议版本号1.2.3是有此问题的，也并非Mapper 3.x的最新版，Release note的更新也较为滞后，辛苦适时更新一下~

这个好使
