### ISSUE TITLE
请问通用mapper如何使用继承

### ISSUE THREAD

**Issue by haozileung** [abel533/Mapper#318]
例如： 
`public interface AdminMapper extends Mapper<Admin>, MySqlMapper<Admin> {
}`

我用通用mapper和generator生成了一个mapper和对应的xml。

然后我想增加新的方法，又不想改动这些文件，因为后面可能会重新生成这部分的内容。

现在有试过新增interface ExAdminMapper extends AdminMapper 和新增对应的xml。

但项目运行会报错：无法获取 xxxx 方法的泛型信息!

`
Caused by: tk.mybatis.mapper.MapperException: 无法获取 com.example.mapper.ExAdminMapper.selectCountByExample 方法的泛型信息!
	at tk.mybatis.mapper.mapperhelper.MapperTemplate.getEntityClass(MapperTemplate.java:179) ~[mapper-core-1.0.2.jar:na]
	at tk.mybatis.mapper.provider.ExampleProvider.selectCountByExample(ExampleProvider.java:50) ~[mapper-base-1.0.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at tk.mybatis.mapper.mapperhelper.MapperTemplate.setSqlSource(MapperTemplate.java:246) ~[mapper-core-1.0.2.jar:na]
	... 28 common frames omitted
`

**Comment by abel533** [comment]
不支持这种情况下的继承。。和实现中获取泛型代码有关。
