### ISSUE TITLE
联合主键，无法启动项目了，报错。。。

### ISSUE THREAD

**Issue by cuivip** [abel533/Mapper#337]
java bean ：
{
    @Id
     private String codeKey;
     @Id
     private String typeKey;
}

`Caused by: tk.mybatis.mapper.MapperException: tk.mybatis.mapper.MapperException: 继承 deleteByIds 方法的实体类[com.opespro.admin.po.SysCode]中必须只有一个带有 @Id 注解的字段
	at tk.mybatis.mapper.mapperhelper.MapperTemplate.setSqlSource(MapperTemplate.java:256) ~[mapper-core-1.0.2.jar:na]
	at tk.mybatis.mapper.mapperhelper.MapperHelper.setSqlSource(MapperHelper.java:375) ~[mapper-core-1.0.2.jar:na]
	... 53 common frames omitted
Caused by: tk.mybatis.mapper.MapperException: 继承 deleteByIds 方法的实体类[com.opespro.admin.po.SysCode]中必须只有一个带有 @Id 注解的字段
	at tk.mybatis.mapper.provider.IdsProvider.deleteByIds(IdsProvider.java:67) ~[mapper-base-1.0.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at tk.mybatis.mapper.mapperhelper.MapperTemplate.setSqlSource(MapperTemplate.java:246) ~[mapper-core-1.0.2.jar:na]
	... 54 common frames omitted`

**Comment by cuivip** [comment]
IdsMapper<T> 
我不继承这个mapper就可以了，从设计上看，多主键对ids提供的功能构成了那些挑战呢？
