### ISSUE TITLE
主键生成时的奇怪问题

### ISSUE THREAD

**Issue by cuivip** [abel533/Mapper#338]
先上代码，我的主键生成类：
```java
public class GeneratorUUID implements GenId<String> {
      public String genId(String table, String column){
          return UUID.randomUUID().toString().replaceAll("-", "") ;
      }
}
```
主键使用方式：
```java
public class SysUser  extends BaseEntity{
     private static final long serialVersionUID = 1L;
     //用户唯一标识
     @Id
     @KeySql(genId = GeneratorUUID.class)
     private String userId;
     //用户登录系统的帐号
     private String account;
     //用户名称，即用户的姓名
     private String userName;
}
```
向数据库新增一条记录时，抛出异常，有事务控制，大概意思如下：

 ```java
@Transactional
 public SysUser add(SysUser sysUser){
        super.add(sysUser);
       //这里可以抛出一个异常，让事务回滚
}
```
再次调用add方法，新增用户，
获得如下异常：
```
2018-06-15 16:52:02.983 ERROR 21316 --- [io-8081-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression '@tk.mybatis.mapper.genid.GenIdUtil@genId(_parameter, 'userId', @com.xxx.base.GeneratorUUID@class, 'sys_user', 'user_id')'. Cause: org.apache.ibatis.ognl.MethodFailedException: Method "genId" failed for object class tk.mybatis.mapper.genid.GenIdUtil [tk.mybatis.mapper.MapperException: 生成 ID 失败!]] with root cause

java.lang.ClassCastException: com.xxx.base.GeneratorUUID cannot be cast to tk.mybatis.mapper.genid.GenId
    at tk.mybatis.mapper.genid.GenIdUtil.genId(GenIdUtil.java:59) ~[mapper-core-1.0.2.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
```

重启spring boot应用后，异常消失。

**Comment by abel533** [comment]
用的什么版本？如果是不是2.0.3-beta1版本，你就换最新的试试。。目前最新版本是2.0.3，和beta1完全一样。

**Comment by abel533** [comment]
测试新版本的时候注意，做个修改让devtools自动重启。

**Comment by cuivip** [comment]
已经解决
