### ISSUE TITLE
spring-boot环境专用代码生成器MyBatis3运行失败

### ISSUE THREAD

**Issue by bughey** [abel533/Mapper#353]
mbg使用tk.mybatis.mapper.generator.MapperPlugin后，context的targetRuntime=MyBatis3时，启动spring-boot报错：
Caused by: java.lang.IllegalArgumentException: Mapped Statements collection already contains value for com.example.mybatissample.domain.mapper.CurrentDeptEmpMapper.selectByExample
	at org.apache.ibatis.session.Configuration$StrictMap.put(Configuration.java:872) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.Configuration$StrictMap.put(Configuration.java:844) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.Configuration.addMappedStatement(Configuration.java:668) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.builder.MapperBuilderAssistant.addMappedStatement(MapperBuilderAssistant.java:302) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parseStatement(MapperAnnotationBuilder.java:351) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parse(MapperAnnotationBuilder.java:134) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.binding.MapperRegistry.addMapper(MapperRegistry.java:72) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.Configuration.addMapper(Configuration.java:741) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.bindMapperForNamespace(XMLMapperBuilder.java:413) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:94) ~[mybatis-3.4.6.jar:3.4.6]
	at org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:521) ~[mybatis-spring-1.3.2.jar:1.3.2]
	... 56 common frames omitted

**Comment by abel533** [comment]
你生成了Example的方法，这些方法和通用Mapper自带的Example方法重复。

**Comment by zbflcy** [comment]
有解决办法吗?
