### ISSUE TITLE
使用Mapper专用的MyBatis Generator插件生成mapper时报错

### ISSUE THREAD

**Issue by wangzhongshan** [abel533/Mapper#42]
### **版本信息：**
mybatis-generator-core版本1.3.4
mapper版本3.3.8

### **generatorConfig.xml配置：**(省略其他MBG原生配置)
```
<plugin type="tk.mybatis.mapper.generator.MapperPlugin">
            <property name="mappers" value="tk.mybatis.mapper.common.Mapper"/>
 </plugin>
```
### **错误信息：**
```
Exception in thread "main" java.lang.AbstractMethodError: tk.mybatis.mapper.generator.MapperCommentGenerator.addModelClassComment(Lorg/mybatis/generator/api/dom/java/TopLevelClass;Lorg/mybatis/generator/api/IntrospectedTable;)V
	at org.mybatis.generator.codegen.mybatis3.model.BaseRecordGenerator.getCompilationUnits(BaseRecordGenerator.java:70)
	at org.mybatis.generator.codegen.mybatis3.IntrospectedTableMyBatis3Impl.getGeneratedJavaFiles(IntrospectedTableMyBatis3Impl.java:233)
	at org.mybatis.generator.config.Context.generateFiles(Context.java:721)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:269)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:139)
	at Gen.GenMain.main(GenMain.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by wangzhongshan** [comment]
用1.3.4版本maven插件也会报错，但是用1.3.2版本的maven插件就可以了。

**Comment by abel533** [comment]
新版本的还没试过，先用低版本吧。

**Comment by mingt** [comment]
有必要尽早把 mybatis-generator-core 升级到 v1.3.4 ，见 #45

**Comment by abel533** [comment]
忘了回复了，新版本已经支持了。

**Comment by wangzhongshan** [comment]
3q，早就升级新版本了。

**Comment by denofiend** [comment]
with gradle plugin apply plugin: "com.arenagod.gradle.MybatisGenerator"

error:
java.lang.AbstractMethodError: tk.mybatis.mapper.generator.MapperCommentGenerator.addModelClassComment

**Comment by NiuZhuang** [comment]
同样的问题
    classpath("gradle.plugin.com.thinkimi.gradle:mybatis-generator-plugin:2.0")

    implementation('tk.mybatis:mapper-spring-boot-starter:2.0.4')    

Receiver class tk.mybatis.mapper.generator.MapperCommentGenerator does not define or inherit an implementation of the resolved method abstract addModelClassComment(Lorg/mybatis/generator/api/dom/java/TopLevelClass;Lorg/mybatis/generator/api/IntrospectedTable;)V of interface org.mybatis.generator.api.CommentGenerator.
