### ISSUE TITLE
采用 assembly 打包后，找不到实体类

### ISSUE THREAD

**Issue by guan25** [abel533/Mapper#423]
```
2018-09-26 21:46:28.094 INFO  [c.z.h.HikariDataSource 110] - HikariPool-1 - Starting...
2018-09-26 21:46:28.238 DEBUG [c.z.h.p.HikariPool 538] - HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@13f6d6b4
2018-09-26 21:46:28.240 INFO  [c.z.h.HikariDataSource 123] - HikariPool-1 - Start completed.
2018-09-26 21:46:28.257 INFO  [c.b.h.m.s.s.i.SecondHouseServiceImpl 219] - <===secondhouse 根据过滤条件查询
2018-09-26 21:46:28.270 ERROR [o.a.j.l.DirectJDKLog 182] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is tk.mybatis.mapper.MapperException: 无法获取实体类com.byjz.housecloud.microservice.secondhouse.model.domain.SecondHouse对应的表名!] with root cause
tk.mybatis.mapper.MapperException: 无法获取实体类com.byjz.housecloud.microservice.secondhouse.model.domain.SecondHouse对应的表名!
        at tk.mybatis.mapper.mapperhelper.EntityHelper.getEntityTable(EntityHelper.java:68)
        at tk.mybatis.mapper.entity.Example.<init>(Example.java:103)
        at tk.mybatis.mapper.entity.Example.<init>(Example.java:88)
        at tk.mybatis.mapper.entity.Example.<init>(Example.java:78)
        at com.byjz.housecloud.common.core.util.DbFilterPro.getFilterExample(DbFilterPro.java:131)
        at com.byjz.housecloud.common.core.util.DbFilterPro.getFilterInfoList(DbFilterPro.java:73)
        at com.byjz.housecloud.common.core.util.DbFilterPro.getFilterInfoList(DbFilterPro.java:52)
        at com.byjz.housecloud.microservice.secondhouse.service.impl.SecondHouseServiceImpl.getHouseList(SecondHouseServiceImpl.java:221)
        at com.byjz.housecloud.microservice.secondhouse.service.impl.SecondHouseServiceImpl$$FastClassBySpringCGLIB$$db1999fe.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at com.byjz.housecloud.microservice.secondhouse.service.impl.SecondHouseServiceImpl$$EnhancerBySpringCGLIB$$7b50e480.getHouseList(<generated>)
        at com.byjz.housecloud.microservice.secondhouse.controller.web.SecondhouseUserController.getUsrSecondHouseFilter(SecondhouseUserController.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
```

pom文件：
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<addMavenDescriptor>false</addMavenDescriptor>
						<manifest>
							<mainClass>com.byjz.housecloud.microservice.secondhouse.HousecloudMicroserviceSecondhouseApplication</mainClass>
							<addClasspath>true</addClasspath>
							<classpathPrefix>../lib/</classpathPrefix>
						</manifest>
						<manifestEntries>
							<Class-Path>../config</Class-Path>
						</manifestEntries>
					</archive>
					<excludes>
						<exclude>static/**</exclude>
						<exclude>*.yml</exclude>
						<exclude>*.properties</exclude>
					</excludes>
				</configuration>
			</plugin>

			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>${maven-assembly-plugin.version}</version>
				<configuration>
					<descriptors>
						<descriptor>src/main/assembly/assembly.xml</descriptor>
					</descriptors>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

**Comment by abel533** [comment]
通常是Mapper没有配置生效导致的。

**Comment by qrqhuang** [comment]
你这个是实体类加载到了， 只是没有找到表吧， 有移交部署吗。

**Comment by DreamPWJ** [comment]
经常出现这种情况  需要经常重启修复
