### ISSUE TITLE
关于selectByPrimaryKey的一个奇怪的问题

### ISSUE THREAD

**Issue by cuivip** [abel533/Mapper#455]
我这里有个角色表，建表语句如下：

```
CREATE TABLE sys_role (
  role_id char(36) NOT NULL COMMENT '角色代码信息',
  role_name varchar(32) NOT NULL COMMENT '角色名称信息',
  role_type varchar(32) NOT NULL COMMENT '角色名称信息',
  order_by int(11) DEFAULT NULL COMMENT '排序',
  valid_flag char(1) DEFAULT NULL COMMENT '有效标记：Y：表示有效；N：表示无效，对应基础数据类型中的“flagType”数据',
  org_id varchar(32) NOT NULL COMMENT '机构代码，用于多帐套，隔离不同机构数据',
  data_version int(5) NOT NULL COMMENT '数据库记录版本号',
  create_by char(36) DEFAULT NULL COMMENT '创建人ID，对应sys_user表中的用户代码[id]',
  create_datetime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建数据时间',
  edit_by char(36) DEFAULT NULL COMMENT '最新修改人ID，对应sys_user表中的用户代码[id]',
  edit_datetime datetime DEFAULT NULL COMMENT '最新修改时间',
  PRIMARY KEY (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色信息表'
```

我的测试语句：

```
                SysRole role = new SysRole();
		 role.setCreateBy("2eca4b3ce5f24e0793768fcecf998330");
		 role.setCreateDatetime(new Date(1541663635000l));
		 role.setDataVersion(2);
		 role.setEditBy("2eca4b3ce5f24e0793768fcecf998330");
		 role.setEditDatetime(new Date(1541747591000l));
		 role.setOrderBy(4556);
		 role.setOrgId("1");
		 role.setRoleId("4261e7773f774d3eaf52ce3d3e2ebcb4");
		 role.setRoleName("DDS");
		 role.setRoleType("ed");
		 role.setValidFlag("Y");
		 try {
			 SysRole sysRole = roleMapper.selectByPrimaryKey(role);
			 System.out.println("sysRole:"+sysRole);
		} catch (Exception e) {
			e.printStackTrace();
		}
```
期望结果是 role id 为 4261e7773f774d3eaf52ce3d3e2ebcb4 的角色数据被查询出来，但这个查询确保存了。日志信息如下：

```
2018-11-09 17:42:04.099 DEBUG 19536 --- [           main] c.o.a.m.S.selectByPrimaryKey             : ==>  Preparing: SELECT data_version, org_id, valid_flag, create_by, create_datetime, edit_by, edit_datetime, role_id, role_name, role_type, order_by FROM sys_role WHERE role_id = ? order by 4556 
2018-11-09 17:42:04.100 DEBUG 19536 --- [           main] c.o.a.m.S.selectByPrimaryKey             : ==> Parameters: 4261e7773f774d3eaf52ce3d3e2ebcb4(String)
2018-11-09 17:42:04.152  INFO 19536 --- [           main] o.s.b.f.xml.XmlBeanDefinitionReader      : Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column '4556' in 'order clause'
### The error may exist in com/opespro/admin/mapper/SysRoleMapper.java (best guess)
### The error may involve com.opespro.admin.mapper.SysRoleMapper.selectByPrimaryKey-Inline
### The error occurred while setting parameters
### SQL: SELECT data_version, org_id, valid_flag, create_by, create_datetime, edit_by, edit_datetime, role_id, role_name, role_type, order_by FROM sys_role WHERE role_id = ? order by 4556
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column '4556' in 'order clause'
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column '4556' in 'order clause'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:234)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy111.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:82)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy116.selectByPrimaryKey(Unknown Source)
	at com.opespro.admin.service.DataVersionTest.test(DataVersionTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column '4556' in 'order clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3051)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3049)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
	at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy181.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:136)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy223.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 38 more
```
难道是因为orderBy这个属性吗？不科学啊！

**Comment by cuivip** [comment]
我在补存下po的代码
```
@Table(name = "sys_role")
public class SysRole  extends BaseEntity{

     private static final long serialVersionUID = 1L;
     /*角色代码信息*/
     @Id
     @KeySql(genId = GeneratorUUID.class)
     private String roleId;
     /*角色名称信息*/
     private String roleName;
     /*角色名称信息*/
     private String roleType;
     /*排序*/
     private Integer orderBy;
     /**
      * 角色代码信息
      * @return
      */
     public String getRoleId() {
         return roleId;  
     }

     public void setRoleId(String roleId) {
          this.roleId = roleId;
     }
     /**
      * 角色名称信息
      * @return
      */
     public String getRoleName() {
         return roleName;  
     }

     public void setRoleName(String roleName) {
          this.roleName = roleName;
     }
     /**
      * 角色名称信息
      * @return
      */
     public String getRoleType() {
         return roleType;  
     }

     public void setRoleType(String roleType) {
          this.roleType = roleType;
     }
     /**
      * 排序
      * @return
      */
     public Integer getOrderBy() {
         return orderBy;  
     }

     public void setOrderBy(Integer orderBy) {
          this.orderBy = orderBy;
     }

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
```
BaseEntity包含了一些公用属性

**Comment by cuivip** [comment]
为什么是这个语句？
SELECT data_version, org_id, valid_flag, create_by, create_datetime, edit_by, edit_datetime, role_id, role_name, role_type, order_by FROM sys_role WHERE role_id = ? order by 4556

**Comment by duwey** [comment]
把orderBy属性加上@Column(name = "order_by")试试看行不行呢

**Comment by qrqhuang** [comment]
没有复现你的问题， 你是哪个版本的`mapper`

**Comment by cuivip** [comment]
我用的是最新版mapper-starter 是 2.0.3

**Comment by cuivip** [comment]
> 把orderBy属性加上@column(name = "order_by") 试试看行不行呢

你有复现出来吗？

**Comment by cuivip** [comment]
> 你用分页插件了吧？？是不是在群里提过？
> 
> 分页插件默认识别 `orderBy` 属性，自动排序。。
> 
> 可以配置 `params` 参数，设置为 `orderBy=xxOrderBy`
> 
> 源码：https://github.com/pagehelper/Mybatis-PageHelper/blob/593646eda0dd47573067eaefdd9f65278d973ccd/src/main/java/com/github/pagehelper/util/PageObjectUtil.java#L59

我没有用分页插件，就是简单的按照主键查询

**Comment by abel533** [comment]
主键查询不会处理 orderby 字段名。
