### ISSUE TITLE
为什么扩展的批量更新出现如下异常？

### ISSUE THREAD

**Issue by xiaozhi404** [abel533/Mapper#490]
Caused by: org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (cn.codemao.edu.contest.common.handler.MyBatchUpdateSelectiveProvider.dynamicSQL).  Cause: java.lang.InstantiationException: cn.codemao.edu.contest.common.handler.MyBatchUpdateSelectiveProvider
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:134) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.getBoundSql(ProviderSqlSource.java:102) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:292) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.statement.BaseStatementHandler.<init>(BaseStatementHandler.java:64) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.<init>(PreparedStatementHandler.java:40) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.<init>(RoutingStatementHandler.java:46) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.Configuration.newStatementHandler(Configuration.java:558) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.4.6.jar:3.4.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63) ~[mybatis-3.4.6.jar:3.4.6]
	at com.sun.proxy.$Proxy279.update(Unknown Source) ~[na:na]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198) ~[mybatis-3.4.6.jar:3.4.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.2.jar:1.3.2]
	... 113 common frames omitted
Caused by: java.lang.InstantiationException: cn.codemao.edu.contest.common.handler.MyBatchUpdateSelectiveProvider
	at java.lang.Class.newInstance(Class.java:427) ~[na:1.8.0_181]
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.invokeProviderMethod(ProviderSqlSource.java:165) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:116) ~[mybatis-3.4.6.jar:3.4.6]
	... 133 common frames omitted
Caused by: java.lang.NoSuchMethodException: cn.codemao.edu.contest.common.handler.MyBatchUpdateSelectiveProvider.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_181]
	at java.lang.Class.newInstance(Class.java:412) ~[na:1.8.0_181]
	... 135 common frames omitted

代码如下：
public interface MyBatchUpdateSelectiveMapper<T> {

    @UpdateProvider(type= MyBatchUpdateSelectiveProvider.class, method="dynamicSQL")
    void batchUpdateSelective(List<T> list);

}

public class MyBatchUpdateSelectiveProvider extends MapperTemplate {

    public MyBatchUpdateSelectiveProvider(Class<?> mapperClass, MapperHelper mapperHelper) {
        super(mapperClass, mapperHelper);
    }

    /*
         拼接如下的SQL语句，可以使每个业务类进行通用使用
        <foreach collection="list" item="record" separator=";" >
            UPDATE tabple_emp
            <set>
              <if test="createdAt != null" >
                created_at = #{createdAt,jdbcType=TIMESTAMP},
              </if>
                emp_name=#{record.empName},
                emp_age=#{record.empAge},
                emp_salary=#{record.empSalary},
            </set>
            where emp_id=#{record.empId}
        </foreach>
     */
    public String batchUpdateSelective(MappedStatement statement) {

        //1.创建StringBuilder用于拼接SQL语句的各个组成部分
        StringBuilder builder = new StringBuilder();

        //2.拼接foreach标签
        builder.append("<foreach collection=\"list\" item=\"record\" separator=\";\" >");

        //3.获取实体类对应的Class对象
        Class<?> entityClass = super.getEntityClass(statement);

        //4.获取实体类在数据库中对应的表名
        String tableName = super.tableName(entityClass);

        //5.生成update子句
        String updateClause = SqlHelper.updateTable(entityClass, tableName);

        builder.append(updateClause);

        builder.append("<set>");

        //6.获取所有字段信息
        Set<EntityColumn> columns = EntityHelper.getColumns(entityClass);

        String idColumn = null;
        String idHolder = null;

        for (EntityColumn entityColumn : columns) {

            boolean isPrimaryKey = entityColumn.isId();

            //7.判断当前字段是否为主键
            if(isPrimaryKey) {

                //8.缓存主键的字段名和字段值
                idColumn = entityColumn.getColumn();
                //※返回格式如:#{record.age,jdbcType=NUMERIC,typeHandler=MyTypeHandler}
                idHolder = entityColumn.getColumnHolder("record");

            }else {
                builder.append("<if test= "+entityColumn.getProperty()+" != null>");
                //9.使用非主键字段拼接SET子句
                String column = entityColumn.getColumn();
                String columnHolder = entityColumn.getColumnHolder("record");

                builder.append(column).append("=").append(columnHolder).append(",");
                builder.append("</if>");
            }

        }
        builder.append("</set>");
        //10.使用前面缓存的主键名、主键值拼接where子句
        builder.append("where ").append(idColumn).append("=").append(idHolder);
        builder.append("</foreach>");
        //11.将拼接好的字符串返回
        return builder.toString();
    }

}

**Comment by Qingtian239113** [comment]
这个问题这么久了每人回复的？

**Comment by biuabiu** [comment]
@Qingtian239113  老兄我也遇到了.你解决没有

**Comment by xiaozhi404** [comment]
> @Qingtian239113 老兄我也遇到了.你解决没有

没有解决，换一种解决方式，放弃tk, 使用mp

**Comment by biuabiu** [comment]
> > @Qingtian239113 老兄我也遇到了.你解决没有
> 
> 没有解决，换一种解决方式，放弃tk, 使用mp

这么暴力吗? 我倒是解决了注入,但是批量更新还是报错 ;加个钉钉?

**Comment by xiaozhi404** [comment]
> > > @Qingtian239113 老兄我也遇到了.你解决没有
> > 
> > 
> > 没有解决，换一种解决方式，放弃tk, 使用mp
> 
> 这么暴力吗? 我倒是解决了注入,但是批量更新还是报错 ;加个钉钉?
钉钉是什么？

**Comment by biuabiu** [comment]
> > > > @Qingtian239113 老兄我也遇到了.你解决没有
> > > 
> > > 
> > > 没有解决，换一种解决方式，放弃tk, 使用mp
> > 
> > 
> > 这么暴力吗? 我倒是解决了注入,但是批量更新还是报错 ;加个钉钉?
> > 钉钉是什么？

算了,放弃了

**Comment by abel533** [comment]
mappers参数配置中没有包含到该方法导致的。
