### ISSUE TITLE
继承通用mapper不能使用spring进行扫描

### ISSUE THREAD

**Issue by NorthFacing** [abel533/Mapper#5]
我封装了一个基类，这个基类继承通用mapper：
```java
package com.yuantu.core.base;
import java.util.List;
import tk.mybatis.mapper.common.Mapper;
import com.yuantu.domain.BaseDomain;
public interface BaseMapper<M extends BaseDomain, VO> extends Mapper<M> {
}
```
然后业务mapper继承这个基类：
```java
package com.yuantu.mapper;
import com.yuantu.core.base.BaseMapper;
import com.yuantu.domain.DemoKey;
import com.yuantu.domain.DemoKeyVo;
public interface DemoKeyMapper extends BaseMapper<DemoKey, DemoKeyVo> {\
}
```
如果将自己封装的BaseMapper和业务DemoKeyMapper，都进行spring的basepackage扫描：
```xml
<property name="basePackage" value="com.yuantu.mapper" />
```
虽然源码中有基类扫描的判断：
```java
……
        if (this.mapperClass == getMapperClass(ms.getId())) {
            throw new RuntimeException("请不要配置或扫描通用Mapper接口类：" + this.mapperClass);
        }
……
```
但并不能拦截到，而是往下继续运行出现如下错误：
```java
Caused by: java.lang.RuntimeException: 调用方法异常:java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
    at tk.mybatis.mapper.mapperhelper.MapperHelper.setSqlSource(MapperHelper.java:247)
	at tk.mybatis.mapper.mapperhelper.MapperHelper.processConfiguration(MapperHelper.java:303)
	at tk.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:23)
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	... 42 more
```
水平不够，因为这个问题，弄了一下午，哎，都是泪……
不知道这个是BUG，还是就应该如此，希望可以将错误提示改进的更加友好一些。

**Comment by NorthFacing** [comment]
解决方法是，将自己封装的基类BaseMapper放到spring扫描不到的地方，也就是basePackage之外的地方就行了。

**Comment by abel533** [comment]
文档中提到过不能扫描基类。。在spring4中可以扫描。。

**Comment by NorthFacing** [comment]
用的是spring4，昨天是单元测试junit测试通过，今天使用maven启动的时候，又出现则个问题了，求指导。

**Comment by BluesJhao** [comment]
配置@MapperScan的markerInterface参数即可

**Comment by liugdxd** [comment]
> 文档中提到过不能扫描基类。。在spring4中可以扫描。。

我把通用mapper放到mapperScan扫描之外的地方了，但是还是这个错

**Comment by abel533** [comment]
@liugdxd 注意所有表对应的Mapper要指定泛型类型。
