### ISSUE TITLE
单元测试使用Example，报无法获取实体类XXX对应表名的错误，请问如何解决？

### ISSUE THREAD

**Issue by five00** [abel533/Mapper#535]
tk.mybatis.mapper.MapperException: 无法获取实体类com.longfor.core.supplier.entity.enterprice.EnterpriceBasicInfo对应的表名!
	at tk.mybatis.mapper.mapperhelper.EntityHelper.getEntityTable(EntityHelper.java:68)
	at tk.mybatis.mapper.entity.Example.<init>(Example.java:103)
	at tk.mybatis.mapper.entity.Example.<init>(Example.java:88)
	at tk.mybatis.mapper.entity.Example.<init>(Example.java:78)
	at com.longfor.core.supplier.service.impl.SupplierAuditServiceImpl.buildRegisterListParam(SupplierAuditServiceImpl.java:131)
	at com.longfor.core.supplier.service.impl.SupplierAuditServiceImpl.queryBaseInfos(SupplierAuditServiceImpl.java:57)
	at com.longfor.core.supplier.service.impl.SupplierAuditServiceImpl.getRegisterSuppliers(SupplierAuditServiceImpl.java:41)
	at com.longfor.core.supplier.service.SupplierAuditServiceTest.getRegisterSuppliersTest(SupplierAuditServiceTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by five00** [comment]
@abel533

**Comment by five00** [comment]
刚刚解决了，需要提前初始化对象
EntityHelper.initEntityNameMap(EnterpriceBasicInfo.class, new Config());
