### ISSUE TITLE
springboot集成后，运行是报错 在系统中发现了多个分页插件，请检查系统配置!

### ISSUE THREAD

**Issue by qiankunshe** [abel533/Mapper#557]
你好，我用下面这个例子的配置集成了项目
https://github.com/abel533/MyBatis-Spring-Boot
运行报错 
`### Cause: java.lang.RuntimeException: 在系统中发现了多个分页插件，请检查系统配置!
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:79) ~[mybatis-spring-1.3.0.jar:1.3.0]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:447) ~[mybatis-spring-1.3.0.jar:1.3.0]
	at com.sun.proxy.$Proxy109.selectList(Unknown Source) ~[?:?]
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:231) ~[mybatis-spring-1.3.0.jar:1.3.0]`

我的配置是
`mybatis:
  type-aliases-package: com.immortalgo.**.model
  mapper-locations: classpath:**/mapper/*.xml

mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql`

jar包配置 
`
/*compile group: 'org.mybatis.spring.boot', name: 'mybatis-spring-boot-starter', version:'1.3.1'*/
    compile group: 'tk.mybatis', name: 'mapper-spring-boot-starter', version: '2.1.5'

    // https://mvnrepository.com/artifact/org.mybatis.spring.boot/mybatis-spring-boot-starter
    compile group: 'org.mybatis.spring.boot', name: 'mybatis-spring-boot-starter', version: '2.0.0'

    compile("com.github.pagehelper:pagehelper-spring-boot-starter:1.2.10")

 compile group: 'org.mybatis', name: 'mybatis', version: '3.4.1'
    compile group: 'org.mybatis.caches', name: 'mybatis-ehcache', version: '1.1.0'
    compile group: 'org.mybatis', name: 'mybatis-spring', version: '1.3.0'
`

**Comment by qiankunshe** [comment]
我的运行代码是
`
public <T> PageVO<T> selectStatementPage(String statement, int pageNum, int pageSize, String order, Object prams) {
        if (StringUtils.isNotEmpty(order)) {
            PageHelper.startPage(pageNum, pageSize, order);
        } else {
            PageHelper.startPage(pageNum, pageSize);
        }
        Page<T> page = (Page<T>) sqlSessionTemplate.selectList(statement, prams);
    
        PageVO<T> pagevo = PageVO.getPageVO();
        long totalPage = page.getTotal() / pageSize + (page.getTotal() % pageSize > 0 ? 1 : 0);
        pagevo.setTotalPage(totalPage);
        pagevo.setTotal(page.getTotal());
        pagevo.setPageNum(page.getPageNum());
        pagevo.setPageSize(page.getPageSize());
        pagevo.setRows(page);
        return pagevo;
    }
`

**Comment by qiankunshe** [comment]
如果项目同时引用 
compile group: 'tk.mybatis', name: 'mapper-spring-boot-starter', version: '2.1.5'
compile("com.github.pagehelper:pagehelper-spring-boot-starter:1.2.10")
就会出现问题，如果只用 mapper-spring-boot-starter 没有错误
