### ISSUE TITLE
自定义通用接口启动报错

### ISSUE THREAD

**Issue by SalamanPhoo** [abel533/Mapper#594]
我自己用@RegisterMapper方式新增了一个修改的接口，但是启动总是报错，请问有大佬知道为什么吗
报错：Caused by: tk.mybatis.mapper.MapperException: tk.mybatis.mapper.provider.base.BaseUpdateProvider中缺少updateByPrimaryFieldsKey方法!
	at tk.mybatis.mapper.mapperhelper.MapperHelper.fromMapperClass(MapperHelper.java:137)
	at tk.mybatis.mapper.mapperhelper.MapperHelper.registerMapper(MapperHelper.java:151)
	at tk.mybatis.mapper.mapperhelper.MapperHelper.registerMapper(MapperHelper.java:157)
	at tk.mybatis.mapper.mapperhelper.MapperHelper.registerMapper(MapperHelper.java:157)
	at tk.mybatis.mapper.mapperhelper.MapperHelper.registerMapper(MapperHelper.java:157)
	at tk.mybatis.mapper.mapperhelper.MapperHelper.hasRegisterMapper(MapperHelper.java:244)
	at tk.mybatis.mapper.mapperhelper.MapperHelper.isExtendCommonMapper(MapperHelper.java:224)
	at tk.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:92)
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1692)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
	... 34 more

**Comment by zxy1994** [comment]
你自定义的接口，需要自己写一个Provider，然后provider里面生成sql的方法和你定义的接口的方法一样
