### ISSUE TITLE
当前实体类不包含名为lambda$1的属性!

### ISSUE THREAD

**Issue by xwd2000** [abel533/Mapper#622]
09:52:54.133 [DsmResponseBodyAdvice.processControllerException] - 当前实体类不包含名为lambda$1的属性!
tk.mybatis.mapper.MapperException: 当前实体类不包含名为lambda$1的属性!
	at tk.mybatis.mapper.entity.Example$Builder.column(Example.java:1056)
	at tk.mybatis.mapper.entity.Example$Builder.transformCriterion(Example.java:1039)
	at tk.mybatis.mapper.entity.Example$Builder.build(Example.java:1018)
	at com.ai.dsm.xc.service.impl.XcInsServiceImpl.listXcIns(XcInsServiceImpl.java:55)
	at com.ai.dsm.xc.controller.XcInsController.list(XcInsController.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at oerServlet.java:901)

**Comment by xwd2000** [comment]
版本是：
<groupId>tk.mybatis</groupId>
			<artifactId>mapper-spring-boot-starter</artifactId>
			<version>2.0.4</version>

**Comment by heshengbang** [comment]
你可以把源代码贴出来，不然很难去判断是什么问题导致的，也没办法去尝试复现你的问题。
