### ISSUE TITLE
InsertMapper-冲突的Bean定义异常问题

### ISSUE THREAD

**Issue by JJFighting** [abel533/Mapper#652]
`Exception in thread "main" org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'insertMapper' for bean class [tk.mybatis.mapper.common.sqlserver.InsertMapper] conflicts with existing, non-compatible bean definition of same name and class [tk.mybatis.mapper.common.base.insert.InsertMapper]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:345)
	at org.mybatis.spring.mapper.ClassPathMapperScanner.checkCandidate(ClassPathMapperScanner.java:236)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:283)
	at org.mybatis.spring.mapper.ClassPathMapperScanner.doScan(ClassPathMapperScanner.java:163)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.scan(ClassPathBeanDefinitionScanner.java:250)
	at org.mybatis.spring.mapper.MapperScannerConfigurer.postProcessBeanDefinitionRegistry(MapperScannerConfigurer.java:317)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
`
为什么这两个Mapper都会被装配，而且还是同名。
Annotation-specified bean name 'insertMapper' for bean class [ **tk.mybatis.mapper.common.sqlserver.InsertMapper** ] conflicts with existing, non-compatible bean definition of same name and class [ **tk.mybatis.mapper.common.base.insert.InsertMapper** ]

**Comment by JJFighting** [comment]
因为我 扫描mapper 的 basePackage 配置范围太大了， `**<property name="basePackage" value="**.mapper"/>**` ，没读过通用mapper源码，把**basePackage** 值设置为自己的mapper，不能同时扫描到 【 **tk.mybatis.mapper.common.sqlserver.InsertMapper**】 【**tk.mybatis.mapper.common.base.insert.InsertMapper** 】这两个mapper

**Comment by qrqhuang** [comment]
这两个tk mapper ， 只是一个标记 ， 不要被spring扫描到
