### ISSUE TITLE
联合查询的时候，个别String类型的字段莫名奇妙的出现了向Double类型的转化，然后就报错了。

### ISSUE THREAD

**Issue by UKUHI** [abel533/Mapper#655]
```
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@731b16d7]
[2019-09-04 11:45:37.138] [DESKTOP-BOH0GMJ discuss-server] [ERROR] [http-nio-8091-exec-2]([org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/discuss].[dispatcherServlet]:]) Servlet.service() for servlet [dispatcherServlet] in context with path [/discuss] threw exception [Request processing failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: Error attempting to get column 'literature_file_path' from result set.  Cause: java.sql.SQLException: Error
; uncategorized SQLException; SQL state [null]; error code [0]; Error; nested exception is java.sql.SQLException: Error] with root cause 
java.lang.NumberFormatException: For input string: "93cd149e-14e8-4363-a20f-33419e843f10.docx"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_211]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_211]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_211]
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeDouble(MysqlTextValueDecoder.java:228) ~[mysql-connector-java-8.0.11.jar:8.0.11]
```

**Comment by abel533** [comment]
`com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeDouble`

可以断点看看为什么。

**Comment by UKUHI** [comment]
谢谢您，问题解决了。自定义的Model忘了加无参和全参构造方法。
