### ISSUE TITLE
deleteByIdList delete all table data,with empty list param

### ISSUE THREAD

**Issue by SimpleChenyh** [abel533/Mapper#723]
When custom Mapper extends DeleteByIdListMapper interface, call deleteByIdList method with an empty list will delete all table data.

I noticed that  the **tk.mybatis.mapper.additional.idlist.IdListProvider** condition use `<where>` instead of `where`.

```
/**
 * 拼接条件
 *
 * @param sql
 * @param entityClass
 */

private void appendWhereIdList(StringBuilder sql, Class<?> entityClass, boolean notEmpty){
    Set<EntityColumn> columnList = EntityHelper.getPKColumns(entityClass);
    if (columnList.size() == 1) {
        EntityColumn column = columnList.iterator().next();
        if(notEmpty){
            sql.append("<bind name=\"notEmptyListCheck\" value=\"@tk.mybatis.mapper.additional.idlist.IdListProvider@notEmpty(");
            sql.append("idList, 'idList 不能为空')\"/>");
        }
        sql.append("<where>"); // use <where> it's dangerous
        sql.append("<foreach collection=\"idList\" item=\"id\" separator=\",\" open=\"");
        sql.append(column.getColumn());
        sql.append(" in ");
        sql.append("(\" close=\")\">");
        sql.append("#{id}");
        sql.append("</foreach>");
        sql.append("</where>");
    } else {
        throw new MapperException("继承 ByIdList 方法的实体类[" + entityClass.getCanonicalName() + "]中必须只有一个带有 @Id 注解的字段");
    }
}
```

But **tk.mybatis.mapper.provider.IdsProvider** condition use `where`
```
/**
     * 根据主键字符串进行删除，类中只有存在一个带有@Id注解的字段
     *
     * @param ms
     * @return
     */
    public String deleteByIds(MappedStatement ms) {
        final Class<?> entityClass = getEntityClass(ms);
        StringBuilder sql = new StringBuilder();
        sql.append(SqlHelper.deleteFromTable(entityClass, tableName(entityClass)));
        Set<EntityColumn> columnList = EntityHelper.getPKColumns(entityClass);
        if (columnList.size() == 1) {
            EntityColumn column = columnList.iterator().next();
            sql.append(" where "); // use where it's safe
            sql.append(column.getColumn());
            sql.append(" in (${_parameter})");
        } else {
            throw new MapperException("继承 deleteByIds 方法的实体类[" + entityClass.getCanonicalName() + "]中必须只有一个带有 @Id 注解的字段");
        }
        return sql.toString();
    }


```

I except that the **tk.mybatis.mapper.additional.idlist.IdListProvider** and  **tk.mybatis.mapper.provider.IdsProvider**  are consistent, Both use `where` instead of `<where>`, `<where>` is very dangerous and unreasonable.

**Comment by abel533** [comment]
有 safeDelete 参数，你可以看看是否对这里的方法有效。

## 3.15 safeDelete
配置为 true 后，delete 和 deleteByExample 都必须设置查询条件才能删除，否则会抛出异常。

配置如下：

safeDelete=true
使用效果：
```
Caused by: tk.mybatis.mapper.MapperException: 通用 Mapper 安全检查: 当前操作的方法没有指定查询条件，不允许执行该操作!
	at tk.mybatis.mapper.util.OGNL.notAllNullParameterCheck(OGNL.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.ibatis.ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:899)
	at org.apache.ibatis.ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1544)
	... 53 more
```
## 3.16 safeUpdate
配置为 true 后，updateByExample 和 updateByExampleSelective 都必须设置查询条件才能删除，否则会抛出异常（org.apache.ibatis.exceptions.PersistenceException）。

updateByPrimaryKey 和 updateByPrimaryKeySelective 由于要求必须使用主键，不存在这个问题。

配置如下：

safeUpdate=true
使用效果：
```
Caused by: tk.mybatis.mapper.MapperException: 通用 Mapper 安全检查: 当前操作的方法没有指定查询条件，不允许执行该操作!
	at tk.mybatis.mapper.util.OGNL.notAllNullParameterCheck(OGNL.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.ibatis.ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:899)
	at org.apache.ibatis.ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1544)
	... 53 more
```

**Comment by SimpleChenyh** [comment]
目前是推荐使用 example 而不是修改tk.mybatis.mapper.additional.idlist.IdListProvide么？

**Comment by SimpleChenyh** [comment]
目前是推荐使用 example 而不是修改tk.mybatis.mapper.additional.idlist.IdListProvide么？

**Comment by abel533** [comment]
没有推荐，自己觉得哪个好用哪个。

**Comment by SimpleChenyh** [comment]
Ok, thank you.
