### ISSUE TITLE
Mapper使用注解方式配置SQL报错。

### ISSUE THREAD

**Issue by Seven4X** [abel533/Mapper#77]
Mapper类
```java
public interface DictMapper extends MyMapper<DictVO> {

    @Select("SELECT * FROM V_CODE_NAME_CODE_VAL V WHERE V.F_CODE_NUM = #{fCodeNum}")
    List<DictVO> getDictValsByNum(String fCodeNum);
}
```
错误信息
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:872)
	at java.lang.StringBuilder.substring(StringBuilder.java:72)
	at tk.mybatis.mapper.mapperhelper.SqlHelper.getAllColumns(SqlHelper.java:237)
	at tk.mybatis.mapper.mapperhelper.SqlHelper.selectAllColumns(SqlHelper.java:249)
	at tk.mybatis.mapper.provider.base.BaseSelectProvider.selectByPrimaryKey(BaseSelectProvider.java:98)
	at sun.reflect.GeneratedMethodAccessor439.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at tk.mybatis.mapper.mapperhelper.MapperTemplate.setSqlSource(MapperTemplate.java:234)
	... 72 more
```

使用版本：
mapper-3.3.6.jar
mybatis-3.3.1.jar

**Comment by abel533** [comment]
SqlHelper 中 237 行代码报错：
```java
    /**
     * 获取所有查询列，如id,name,code...
     *
     * @param entityClass
     * @return
     */
    public static String getAllColumns(Class<?> entityClass) {
        Set<EntityColumn> columnList = EntityHelper.getColumns(entityClass);
        StringBuilder sql = new StringBuilder();
        for (EntityColumn entityColumn : columnList) {
            sql.append(entityColumn.getColumn()).append(",");
        }
        return sql.substring(0, sql.length() - 1);
    }
```
你在 return 这里断点看看为什么 sql 空。

**Comment by Seven4X** [comment]
现在解决了， 好像是我DictVO 没有使用注解@Entity
