### ISSUE TITLE
实体Bean不能被强转成实体Bean,问题解决

### ISSUE THREAD

**Issue by helloLI4015** [abel533/Mapper#86]
实体Bean不能被强转成实体Bean。
堆栈如下：
` java.lang.ClassCastException: com.shuangdj.dao.pojo.Users cannot be cast to com.shuangdj.dao.pojo.Users
	at com.shuangdj.service.impl.UserServiceImpl.getUser(UserServiceImpl.java:28)
	at com.shuangdj.controller.HelloWorldController.getUser(HelloWorldController.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)`
META-INF/spring-devtools.properties下排除实体类包不行，
必须在META-INF/spring-devtools.properties下添加下方可。
`restart.include.companycommonlibs=tk/mybatis.*`

**Comment by abel533** [comment]
谢谢提供的解决方案，项目首页已经添加类似内容。
