### ISSUE TITLE
不支持spring native  graalvm 新引擎

### ISSUE THREAD

**Issue by DreamPWJ** [abel533/Mapper#927]
打包报错  `14:10:31  	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
14:10:31  	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
14:10:31  	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
14:10:31  	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
14:10:31  	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
14:10:31  	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
14:10:31  	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
14:10:31  Caused by: org.springframework.aot.generate.UnsupportedTypeValueCodeGenerationException: Code generation does not support tk.mybatis.mapper.mapperhelper.MapperHelper`

**Comment by DreamPWJ** [comment]
@abel533   spring native是主流大趋势了   基建都基于mapper
